CREATE TABLE [dbo].[TB_PRODUCTS_PLATAFORM]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ProductId] INT NOT NULL, 
	[PlataformId] INT NOT NULL, 
    [Path] VARCHAR(MAX) NULL,
    [Metadados] VARCHAR(MAX) NULL,
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK_TB_PRODUCTS_PLATAFORM_PRODUCTS] FOREIGN KEY ([ProductId]) REFERENCES [TB_PRODUCTS]([Id]),
    CONSTRAINT [FK_TB_PRODUCTS_PLATAFORM_PLATAFORM] FOREIGN KEY ([PlataformId]) REFERENCES [TB_PLATAFORMS]([Id])
)
