CREATE TABLE [dbo].[TB_STRATEGIES]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[PlataformId] INT NOT NULL,
	[Kind] INT NOT NULL,
    [Parameter] VARCHAR(MAX),
	[Weight] INT NOT NULL DEFAULT 0,
    [Metadados] VARCHAR(MAX) NULL,
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK_TB_STRATEGIES_PLATAFORMS] FOREIGN KEY ([PlataformId]) REFERENCES [TB_PLATAFORMS]([Id])
)
